export default ActionType = {
  GET_COMMENTS: 'getComments',
  COMMENT: 'comment',
  GET_DISHES: 'getDishes',
  LIKE: 'like',
  DISLIKE: 'dislike',
  ADD_DISH: 'addDish',
  REGISTER: 'register',
  LOGING_IN_WITH_TOKEN: 'loginWithToken',
  LOGING_IN_NO_TOKEN: 'loginNoToken',
  GET_USER_INFO_ID: 'getUserInfoByID',
  GET_USER_INFO_NICKNAME: 'getUserInfoByNickName',
  LOG_OUT: 'logOut',
  GET_DISH_ID: 'GetDishByID',
}